config/routes.rb
SimpleFinancialControl::Application.routes.draw do |map|
    resources :lancamentos
    resources :tipo_lancamentos
    resources :tipo_lancamentos
    resources :tipo_contas
    resources :contas
    match 'saldo/:id' => 'saldo#index'
    match 'saldo/:id/:ano/:mes/:dia' => 'saldo#index'
    match 'transferencia' => 'transferencia#index'
    match 'contas/lancamentos/:id' => 'contas#lancamentos'
    match 'contas/lancamentos/:id/:ano/:mes/:dia' => 'contas#lancamentos'
    match '/' => 'contas#index'
    match '/:controller(/:action(/:id))'

end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base
  belongs_to :tipo_lancamento
  belongs_to :conta
  
  validates_presence_of :valor, :data, :tipo_lancamento, :credito_debito, :conta
  validates_numericality_of :valor
  
  def credito_debito_desc
    if credito_debito == 'c'
      'credito'
    else
      'debito'
    end
  end
end

app/controllers/lancamentos_controller.rb
class LancamentosController < ApplicationController
  layout "sfc"
  # GET /lancamentos
  # GET /lancamentos.xml
  def index
    @lancamentos = Lancamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lancamentos }
    end
  end

  # GET /lancamentos/1
  # GET /lancamentos/1.xml
  def show
    @lancamento = Lancamento.find(params[:id])
    respond_to do |format|
      format.js
      format.html # show.html.erb
      format.xml  { render :xml => @lancamento }
    end
  end

  # GET /lancamentos/new
  # GET /lancamentos/new.xml
  def new
    @lancamento = Lancamento.new
    
    conta = Conta.find_by_id(params[:conta_id]) if params[:conta_id]
    @lancamento.conta = conta
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lancamento }
    end
  end

  # GET /lancamentos/1/edit
  def edit
    @lancamento = Lancamento.find(params[:id])
  end

  # POST /lancamentos
  # POST /lancamentos.xml
  def create
    @lancamento = Lancamento.new(params[:lancamento])

    respond_to do |format|
      if @lancamento.save
        flash[:notice] = 'Lancamento foi criado com sucesso!'
        format.html { redirect_to(lancamentos_path) }
        format.xml  { render :xml => @lancamento, :status => :created, :location => @lancamento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lancamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lancamentos/1
  # PUT /lancamentos/1.xml
  def update
    @lancamento = Lancamento.find(params[:id])

    respond_to do |format|
      if @lancamento.update_attributes(params[:lancamento])
        flash[:notice] = 'Lancamento foi criado com sucesso!'
        format.html { redirect_to(@lancamento) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lancamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lancamentos/1
  # DELETE /lancamentos/1.xml
  def destroy
    @lancamento = Lancamento.find(params[:id])
    @lancamento.destroy

    respond_to do |format|
      format.html { redirect_to(lancamentos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/views/lancamentos/_details.html.erb
<p>
  <b>Valor:</b>
  <%=h @lancamento.valor %>
</p>

<p>
  <b>Data:</b>
  <%=h @lancamento.data %>
</p>

<p>
  <b>Descricao:</b>
  <%=h @lancamento.descricao %>
</p>

<p>
  <b>Tipo lancamento:</b>
  <%=h @lancamento.tipo_lancamento.nome %>
</p>

<p>
  <b>Conta:</b>
  <%=h @lancamento.conta.nome %>
</p>

<p>
  <b>Credito debito:</b>
  <%=h @lancamento.credito_debito_desc %>
</p>

app/views/lancamentos/_show.html.erb
<%= render(:partial => "details")%>

<%= link_to_remote 'Lancamentos', :url => {:controller => "contas", :action => "lancamentos", :id => @lancamento.conta.id} %>

app/views/lancamentos/edit.html.erb
<h1>Editing lancamento</h1>

<% form_for(@lancamento) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </p>
  <p>
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </p>
  <p>
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.label :tipo_lancamento_id %><br />
    <%= f.text_field :tipo_lancamento_id %>
  </p>
  <p>
    <%= f.label :conta_id %><br />
    <%= f.text_field :conta_id %>
  </p>
  <p>
    <%= f.label :credito_debito %><br />
    <%= f.text_field :credito_debito %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @lancamento %> |
<%= link_to 'Back', lancamentos_path %>

app/views/lancamentos/index.html.erb
<h1>Listing lancamentos</h1>

<table>
  <tr>
    <th>Valor</th>
    <th>Data</th>
    <th>Descricao</th>
    <th>Tipo lancamento</th>
    <th>Conta</th>
    <th>Credito debito</th>
  </tr>

<% @lancamentos.each do |lancamento| %>
  <tr>
    <td><%=h lancamento.valor %></td>
    <td><%=h lancamento.data %></td>
    <td><%=h lancamento.descricao %></td>
    <td><%=h lancamento.tipo_lancamento_id %></td>
    <td><%=h lancamento.conta_id %></td>
    <td><%=h lancamento.credito_debito %></td>
    <td><%= link_to 'Show', lancamento %></td>
    <td><%= link_to 'Edit', edit_lancamento_path(lancamento) %></td>
    <td><%= link_to 'Destroy', lancamento, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New lancamento', new_lancamento_path %>

app/views/lancamentos/new.html.erb
<h1>Novo lançamento</h1>

<% form_for(@lancamento) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </p>
  <p>
    <%= f.label :data %><br />
    <%= f.date_select :data, :order => [:day, :month, :year] %>
  </p>
  <p>
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.label :tipo_lancamento_id %><br />
    <%= select("lancamento", "tipo_lancamento_id", TipoLancamento.all.collect{|t| [t.nome, t.id]}, {:prompt => 'Selecione...'}) %> - <%= link_to 'Cadastrar novo tipo de lançamento', new_tipo_lancamento_path %>
  </p>
  <p>
    <%= f.label :conta_id %><br />
    <%= select("lancamento", "conta_id", 
	Conta.all.collect {|c| [ c.nome, c.id ] }, {:prompt => 'Selecione...'}) %></p>
  <p>
    <%= f.label :credito_debito %><br />
    <%= select("lancamento", "credito_debito", 
	[['Crédito', "c"], ['Débito', "d"]], {:prompt => 'Selecione...'}) %>
  </p>
  <p>
    <%= f.submit 'Cadastrar' %>
  </p>
<% end %>

<%= link_to 'Voltar', lancamentos_path %>

app/views/lancamentos/show.html.erb
<p>
  <b>Valor:</b>
  <%=h @lancamento.valor %>
</p>

<p>
  <b>Data:</b>
  <%=h @lancamento.data %>
</p>

<p>
  <b>Descricao:</b>
  <%=h @lancamento.descricao %>
</p>

<p>
  <b>Tipo lancamento:</b>
  <%=h @lancamento.tipo_lancamento.nome %>
</p>

<p>
  <b>Conta:</b>
  <%=h @lancamento.conta.nome %>
</p>

<p>
  <b>Credito debito:</b>
  <%=h @lancamento.credito_debito_desc %>
</p>


<%= link_to 'Edit', edit_lancamento_path(@lancamento) %> |
<%= link_to 'Back', lancamentos_path %>