config/routes.rb
SimpleFinancialControl::Application.routes.draw do |map|
    resources :lancamentos
    resources :tipo_lancamentos
    resources :tipo_lancamentos
    resources :tipo_contas
    resources :contas
    match 'saldo/:id' => 'saldo#index'
    match 'saldo/:id/:ano/:mes/:dia' => 'saldo#index'
    match 'transferencia' => 'transferencia#index'
    match 'contas/lancamentos/:id' => 'contas#lancamentos'
    match 'contas/lancamentos/:id/:ano/:mes/:dia' => 'contas#lancamentos'
    match '/' => 'contas#index'
    match '/:controller(/:action(/:id))'

end

app/models/conta.rb
class Conta < ActiveRecord::Base
  belongs_to :tipo_conta
  has_many :lancamentos
  
  validates_uniqueness_of :nome
  validates_presence_of :nome, :tipo_conta, :valor_inicial
  validates_numericality_of :valor_inicial
  
  CRITERIOS_TOTAL_LANCAMENTOS = "data <= ? AND credito_debito = ?"

  def saldo data_saldo = Date.today
    credito = lancamentos.sum :valor, :conditions => 
    [CRITERIOS_TOTAL_LANCAMENTOS, data_saldo, 'c']
    
    debito  = lancamentos.sum :valor, :conditions => 
    [CRITERIOS_TOTAL_LANCAMENTOS, data_saldo, 'd']
    
    valor_inicial + (credito - debito)
  end
end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  layout "sfc"
  
  # GET /contas
  # GET /contas.xml
  def index
    @contas = Conta.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contas }
    end
  end

  # GET /contas/1
  # GET /contas/1.xml
  def show
    @conta = Conta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @conta }
    end
  end

  # GET /contas/new
  # GET /contas/new.xml
  def new
    @conta = Conta.new
    @tipo_contas = TipoConta.find(:all)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @conta }
    end
  end

  # GET /contas/1/edit
  def edit
    @tipo_contas = TipoConta.find(:all)
    @conta = Conta.find(params[:id])
  end

  # POST /contas
  # POST /contas.xml
  def create
    @conta = Conta.new(params[:conta])

    respond_to do |format|
      if @conta.save
        flash[:notice] = "Conta #{@conta.nome} foi criado com sucesso!"
        format.html { redirect_to(contas_path) }
        format.xml  { render :xml => @conta, :status => :created, :location => @conta }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @conta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contas/1
  # PUT /contas/1.xml
  def update
    @conta = Conta.find(params[:id])

    respond_to do |format|
      if @conta.update_attributes(params[:conta])
        flash[:notice] = "Conta #{@conta.nome} foi atualizado com sucesso!"
        format.html { redirect_to(@conta) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @conta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contas/1
  # DELETE /contas/1.xml
  def destroy
    @conta = Conta.find(params[:id])
    @conta.destroy

    respond_to do |format|
      format.html { redirect_to(contas_url) }
      format.xml  { head :ok }
    end
  end
  
  def lancamentos
    @conta = Conta.find(params[:id])
    if params[:ano] and params[:mes] and params[:dia]
	  @lancamentos = @conta.lancamentos.find(
        :all, 
        :conditions => ["data = ?", Date.new(params[:ano].to_i, params[:mes].to_i, params[:dia].to_i)]
      )
    else
      @lancamentos = @conta.lancamentos
    end
    respond_to do |format|
      format.js
      format.html
    end
    
  end
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/views/contas/_lancamentos.html.erb
<a href="#" onclick="$('lancamentos').style.display='none'">fechar</a>
<h3>Lancamentos da conta: <%= @conta.nome %></h3>

<%= render(:partial => 'lista_lancamentos')%>

<br />

app/views/contas/_lista_lancamentos.html.erb
<table>
  <tr>
    <th>Valor</th>
    <th>Data</th>
    <th>Descricao</th>
    <th>Tipo lancamento</th>
    <th>Conta</th>
    <th>Origem</th>
  </tr>

<% @lancamentos.each do |lancamento| %>
  <tr>
    <td><%=h lancamento.valor %></td>
    <td><%=h lancamento.data %></td>
    <td><%=h lancamento.descricao %></td>
    <td><%=h lancamento.tipo_lancamento.nome %></td>
    <td><%=h lancamento.conta.nome %></td>
    <td><%=h lancamento.credito_debito_desc %></td>
    <td><%= link_to_remote 'Mostrar', :url => lancamento_url(:id => lancamento), :method => :get %></td>
    <td><%= link_to 'Editar', edit_lancamento_path(lancamento) %></td>
    <td><%= link_to 'Apagar', lancamento, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/contas/edit.html.erb
<h1>Editar conta</h1>

<% form_for(@conta) do |f| %>
  <%= f.error_messages %>
  <table>
	<tr>
		<td><%= f.label :nome %></td>
		<td><%= f.text_field :nome %></td>
	</tr>
	<tr>
		<td><%= f.label :descricao %></td>
		<td><%= f.text_field :descricao %></td>
	</tr>
	<tr>
		<td><%= f.label :tipo_conta %></td>
		<td><%= select("conta", "tipo_conta_id", 
		@tipo_contas.collect {|t| [ t.nome, t.id ] }, {:prompt => 'Selecione...'}) %></td>
	</tr>
	<tr>
		<td><%= f.label :valor_inicial %></td>
		<td><%= f.text_field :valor_inicial %></td>
	</tr>
  </table>
  <p>
    <%= f.submit 'Atualizar' %>
  </p>
<% end %>

<%= link_to 'Mostrar', @conta %> |
<%= link_to 'Voltar', contas_path %>

app/views/contas/index.html.erb
<h1>Listar contas</h1>

<div id="lancamentos" style="display:none">
</div>

<table cellspacing="5">
  <tr>
	<th>Nome</th>
	<th>Descricoes</th>
	<th>Tipo Conta</th>
	<th>Valor Inicial</th>
	<th>Saldo Atual</th>
	<th colspan="3">Opcoes</th>
	<th colspan="2">Lancamento</th>
	<th colspan="2">Transferencias</th>
  </tr>
  <tr>
  	<th colspan="5"></th>
	<th colspan="3"></th>
	<th>Todos</th>
	<th>Novo</th>
	<th>De</th>
	<th>Para</th>
  </tr>
<% form_tag "/transferencia", :method => "post" do %>
<% @contas.each do |conta| %>
  <tr>
	<td><%= conta.nome%></td>
	<td><%= conta.descricao%></td>
	<td><%= conta.tipo_conta.nome %></td>
	<td><%= conta.valor_inicial %></td>
	<td><%= conta.saldo %></td>
    <td><%= link_to 'Mostrar', conta %></td>
    <td><%= link_to 'Editar', edit_conta_path(conta) %></td>
    <td><%= link_to 'Apagar', conta, :confirm => 'Are you sure?', :method => :delete %></td>
	<td><%= link_to_remote 'Lancamentos', :url => {:action => "lancamentos", :id => conta.id} %></td>
	<td><%= link_to 'Novo', :controller => 'lancamentos', :action => 'new', :conta_id => conta.id %></td>
	<td align="center"><%= radio_button_tag :conta_de, conta.id%></td>
	<td align="center"><%= radio_button_tag :conta_para, conta.id%></td>
  </tr>
<% end %>

</table>
<p>
<%= submit_tag "Transferir" %>
</p>
<% end %>

<br />

<%= link_to 'Nova conta', new_conta_path %>

app/views/contas/lancamentos.html.erb
<h1>Listando Lancamentos da conta: <%= @conta.nome %></h1>

<%= render(:partial => 'lista_lancamentos')%>

<br />

app/views/contas/new.html.erb
<h1>Nova conta</h1>

<% form_for(@conta) do |f| %>
  <%= f.error_messages %>
  <table>
	<tr>
		<td><%= f.label :nome %></td>
		<td><%= f.text_field :nome %></td>
	</tr>
	<tr>
		<td><%= f.label :descricao %></td>
		<td><%= f.text_field :descricao %></td>
	</tr>
	<tr>
		<td><%= f.label :tipo_conta %></td>
		<td><%= select("conta", "tipo_conta_id", 
		@tipo_contas.collect {|t| [ t.nome, t.id ] }, {:prompt => 'Selecione...'}) %></td>
	</tr>
	<tr>
		<td><%= f.label :valor_inicial %></td>
		<td><%= f.text_field :valor_inicial %></td>
	</tr>
  </table>
  

  <p>
    <%= f.submit 'Cadastrar Conta' %>
  </p>
<% end %>

<%= link_to 'Voltar', contas_path %>

app/views/contas/show.html.erb
<table>
	<tr>
		<td>Nome:</td>
		<td><%= @conta.nome %></td>
	</tr>
	<tr>
		<td>Descrição: </td>
		<td><%= @conta.descricao %></td>
	</tr>
	<tr>
		<td>Tipo Conta: </td>
		<td><%= @conta.tipo_conta.nome %></td>
	</tr>
	<tr>
		<td>Valor Inicial: </td>
		<td><%= @conta.valor_inicial %></td>
	</tr>	
</table>


<%= link_to 'Editar', edit_conta_path(@conta) %> |
<%= link_to 'Voltar', contas_path %>