config/routes.rb
SimpleFinancialControl::Application.routes.draw do |map|
    resources :lancamentos
    resources :tipo_lancamentos
    resources :tipo_lancamentos
    resources :tipo_contas
    resources :contas
    match 'saldo/:id' => 'saldo#index'
    match 'saldo/:id/:ano/:mes/:dia' => 'saldo#index'
    match 'transferencia' => 'transferencia#index'
    match 'contas/lancamentos/:id' => 'contas#lancamentos'
    match 'contas/lancamentos/:id/:ano/:mes/:dia' => 'contas#lancamentos'
    match '/' => 'contas#index'
    match '/:controller(/:action(/:id))'

end

app/models/tipo_conta.rb
class TipoConta < ActiveRecord::Base
  has_many :contas
  
  validates_uniqueness_of :nome
  validates_presence_of :nome
end

app/controllers/tipo_contas_controller.rb
class TipoContasController < ApplicationController
  layout "sfc"
  # GET /tipo_contas
  # GET /tipo_contas.xml
  def index
    @tipo_contas = TipoConta.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tipo_contas }
    end
  end

  # GET /tipo_contas/1
  # GET /tipo_contas/1.xml
  def show
    @tipo_conta = TipoConta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tipo_conta }
    end
  end

  # GET /tipo_contas/new
  # GET /tipo_contas/new.xml
  def new
    @tipo_conta = TipoConta.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tipo_conta }
    end
  end

  # GET /tipo_contas/1/edit
  def edit
    @tipo_conta = TipoConta.find(params[:id])
  end

  # POST /tipo_contas
  # POST /tipo_contas.xml
  def create
    @tipo_conta = TipoConta.new(params[:tipo_conta])

    respond_to do |format|
      if @tipo_conta.save
        flash[:notice] = 'TipoConta was successfully created.'
        format.html { redirect_to(tipo_contas_path) }
        format.xml  { render :xml => @tipo_conta, :status => :created, :location => @tipo_conta }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tipo_conta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_contas/1
  # PUT /tipo_contas/1.xml
  def update
    @tipo_conta = TipoConta.find(params[:id])

    respond_to do |format|
      if @tipo_conta.update_attributes(params[:tipo_conta])
        flash[:notice] = 'TipoConta was successfully updated.'
        format.html { redirect_to(tipo_contas_path) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tipo_conta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_contas/1
  # DELETE /tipo_contas/1.xml
  def destroy
    @tipo_conta = TipoConta.find(params[:id])
    @tipo_conta.destroy

    respond_to do |format|
      format.html { redirect_to(tipo_contas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tipo_contas_helper.rb
module TipoContasHelper
end

app/views/tipo_contas/edit.html.erb
<h1>Editing tipo_conta</h1>

<% form_for(@tipo_conta) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @tipo_conta %> |
<%= link_to 'Back', tipo_contas_path %>

app/views/tipo_contas/index.html.erb
<h1>Listando os tipos de conta</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
  </tr>

<% @tipo_contas.each do |tipo_conta| %>
  <tr>
    <td><%=h tipo_conta.nome %></td>
    <td><%=h tipo_conta.descricao %></td>
    <td><%= link_to 'Show', tipo_conta %></td>
    <td><%= link_to 'Edit', edit_tipo_conta_path(tipo_conta) %></td>
    <td><%= link_to 'Destroy', tipo_conta, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo tipo de conta', new_tipo_conta_path %>

app/views/tipo_contas/new.html.erb
<h1>New tipo_conta</h1>

<% form_for(@tipo_conta) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', tipo_contas_path %>

app/views/tipo_contas/show.html.erb
<p>
  <b>Nome:</b>
  <%=h @tipo_conta.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%=h @tipo_conta.descricao %>
</p>


<%= link_to 'Edit', edit_tipo_conta_path(@tipo_conta) %> |
<%= link_to 'Back', tipo_contas_path %>