config/routes.rb
SimpleFinancialControl::Application.routes.draw do |map|
    resources :lancamentos
    resources :tipo_lancamentos
    resources :tipo_lancamentos
    resources :tipo_contas
    resources :contas
    match 'saldo/:id' => 'saldo#index'
    match 'saldo/:id/:ano/:mes/:dia' => 'saldo#index'
    match 'transferencia' => 'transferencia#index'
    match 'contas/lancamentos/:id' => 'contas#lancamentos'
    match 'contas/lancamentos/:id/:ano/:mes/:dia' => 'contas#lancamentos'
    match '/' => 'contas#index'
    match '/:controller(/:action(/:id))'

end

app/models/tipo_lancamento.rb
class TipoLancamento < ActiveRecord::Base
  has_many :lancamento
  
  validates_uniqueness_of :nome
  validates_presence_of :nome
end

app/controllers/tipo_lancamentos_controller.rb
class TipoLancamentosController < ApplicationController
  layout "sfc"
  # GET /tipo_lancamentos
  # GET /tipo_lancamentos.xml
  def index
    @tipo_lancamentos = TipoLancamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tipo_lancamentos }
    end
  end

  # GET /tipo_lancamentos/1
  # GET /tipo_lancamentos/1.xml
  def show
    @tipo_lancamento = TipoLancamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tipo_lancamento }
    end
  end

  # GET /tipo_lancamentos/new
  # GET /tipo_lancamentos/new.xml
  def new
    @tipo_lancamento = TipoLancamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tipo_lancamento }
    end
  end

  # GET /tipo_lancamentos/1/edit
  def edit
    @tipo_lancamento = TipoLancamento.find(params[:id])
  end

  # POST /tipo_lancamentos
  # POST /tipo_lancamentos.xml
  def create
    @tipo_lancamento = TipoLancamento.new(params[:tipo_lancamento])

    respond_to do |format|
      if @tipo_lancamento.save
        flash[:notice] = 'TipoLancamento was successfully created.'
        format.html { redirect_to(tipo_lancamentos_path) }
        format.xml  { render :xml => @tipo_lancamento, :status => :created, :location => @tipo_lancamento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tipo_lancamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_lancamentos/1
  # PUT /tipo_lancamentos/1.xml
  def update
    @tipo_lancamento = TipoLancamento.find(params[:id])

    respond_to do |format|
      if @tipo_lancamento.update_attributes(params[:tipo_lancamento])
        flash[:notice] = 'TipoLancamento was successfully updated.'
        format.html { redirect_to(@tipo_lancamento) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tipo_lancamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_lancamentos/1
  # DELETE /tipo_lancamentos/1.xml
  def destroy
    @tipo_lancamento = TipoLancamento.find(params[:id])
    @tipo_lancamento.destroy

    respond_to do |format|
      format.html { redirect_to(tipo_lancamentos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tipo_lancamentos_helper.rb
module TipoLancamentosHelper
end

app/views/tipo_lancamentos/edit.html.erb
<h1>Editing tipo_lancamento</h1>

<% form_for(@tipo_lancamento) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @tipo_lancamento %> |
<%= link_to 'Back', tipo_lancamentos_path %>

app/views/tipo_lancamentos/index.html.erb
<h1>Listing tipo_lancamentos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
  </tr>

<% @tipo_lancamentos.each do |tipo_lancamento| %>
  <tr>
    <td><%=h tipo_lancamento.nome %></td>
    <td><%=h tipo_lancamento.descricao %></td>
    <td><%= link_to 'Show', tipo_lancamento %></td>
    <td><%= link_to 'Edit', edit_tipo_lancamento_path(tipo_lancamento) %></td>
    <td><%= link_to 'Destroy', tipo_lancamento, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New tipo_lancamento', new_tipo_lancamento_path %>

app/views/tipo_lancamentos/new.html.erb
<h1>New tipo_lancamento</h1>

<% form_for(@tipo_lancamento) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', tipo_lancamentos_path %>

app/views/tipo_lancamentos/show.html.erb
<p>
  <b>Nome:</b>
  <%=h @tipo_lancamento.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%=h @tipo_lancamento.descricao %>
</p>


<%= link_to 'Edit', edit_tipo_lancamento_path(@tipo_lancamento) %> |
<%= link_to 'Back', tipo_lancamentos_path %>